version: '3'

tasks:
  help:
    desc: Show all available tasks
    cmds:
      - task --list

  build:
    desc: Build and package all projects for deployment
    deps: [app:build, web:build]
    cmds:
      - echo "All projects built!"
  
  test:
    desc: Run all tests
    deps: [app:test, web:test]
    cmds:
      - echo "Ran all tests"

  lint:
    desc: Lint and type-check the codebase
    deps: [app:lint, web:lint]
    cmds:
      - echo "Linted and type-checked the codebase"

  # API tasks
  app:test:
    desc: Run backend tests with pytest
    dir: api
    cmds:
      - poetry run pytest

  app:dev:
    desc: Start backend dev server (uvicorn, hot reload)
    dir: api
    cmds:
      - poetry run uvicorn app:my_app --host 0.0.0.0 --reload

  app:install:
    desc: Install backend dependencies
    dir: api
    cmds:
      - poetry install

  app:build:
    desc: Build backend (customize as needed)
    dir: api
    cmds:
      - echo "Build backend here"

  app:lint:
    desc: Lint and type-check the backend codebase
    dir: api
    cmds:
      - poetry run ruff check .
      - poetry run mypy .

  # Admin CLI
  admin:
    desc: Run TEMPLATE_CLI_NAME CLI in the api directory (forwards all arguments)
    dir: api
    cmds:
      - poetry run TEMPLATE_CLI_NAME {{.CLI_ARGS}}
    silent: false

  # Web tasks
  web:test:
    desc: Run frontend tests with vitest
    dir: web
    cmds:
      - yarn test

  web:dev:
    desc: Start frontend dev server (vite/next)
    dir: web
    cmds:
      - yarn dev

  web:install:
    desc: Install frontend dependencies
    dir: web
    cmds:
      - yarn install

  web:build:
    desc: Build frontend (customize as needed)
    dir: web
    cmds:
      - yarn build

  web:lint:
    desc: Lint and type-check the frontend codebase
    dir: web
    cmds:
      - yarn lint
      - yarn tsc --noEmit

  # DB tasks
  db:dev:
    desc: Start database with Docker Compose
    dir: db
    cmds:
      - docker compose up

  release:
    desc: Create a versioned release tarball and upload to GitHub Releases
    cmds:
      - VERSION=$(grep '^version =' api/pyproject.toml | cut -d'"' -f2)
      - git tag "v$VERSION"
      - git push origin "v$VERSION"
      - tar --exclude='.git' --exclude='.venv' --exclude='node_modules' --exclude='*.pyc' --exclude='*.log' -czf "template-$VERSION.tar.gz" .
      - gh release create "v$VERSION" "template-$VERSION.tar.gz" --title "v$VERSION" --notes "Release $VERSION"

  release:latest:
    desc: Create a tarball for the latest release (template-latest.tar.gz)
    cmds:
      - tar --exclude='.git' --exclude='.venv' --exclude='node_modules' --exclude='*.pyc' --exclude='*.log' -czf "template-latest.tar.gz" .

