version: '3.8'

services:
  postgres:
    image: postgres:16
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    ports:
      - "5432:5432"
    volumes:
      - TEMPLATE_DOCKER_VOLUME:/var/lib/postgresql/data

volumes:
  TEMPLATE_DOCKER_VOLUME:
    name: TEMPLATE_DOCKER_VOLUME
